name: app_ui_kit_example
description: Detailed catalog example for app_ui_kit components.
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  app_ui_kit:
    path: ..
  flutter:
    sdk: flutter
  toastification: ^3.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
